#!/usr/bin/env python3
"""Add survey-based context rows to UltraFeedback preference data."""

import os
import random
from copy import deepcopy
from dataclasses import dataclass, field
from typing import Optional

import numpy as np
import torch
from datasets import concatenate_datasets, load_dataset
from tqdm import tqdm
from transformers import HfArgumentParser


@dataclass
class ScriptArguments:
    output_dir: Optional[str] = field(
        metadata={"help": "Directory where the new dataset will be stored."},
    )
    data_path: str = field(
        metadata={"help": "Directory where the original data is stored."}
    )
    data_subset: str = field(
        default="helpful",
        metadata={"help": "Which subset of the data to use."},
    )
    data_split: str = field(
        default="test",
        metadata={"help": "Which split of the data to use."},
    )
    dataset_size: int = field(
        default=0,
        metadata={"help": "The size of the subset of the data to use"},
    )
    model_type: str = field(
        default="none",
        metadata={"help": "Embedding backbone name."}
    )
    embed_dim: int = field(
        default=4096,
        metadata={"help": "Dimension of the embeddings generated by the LLM."}
    )
    max_length: int = field(
        default=1024,
        metadata={"help": "Maximum token length of the inputs."}
    )
    with_embeddings: bool = field(
        default=True,
        metadata={"help": "Whether embeddings are generated during preprocessing."}
    )
    synthetic_dataset: bool = field(
        default=False,
        metadata={"help": "Whether a synthetic dataset is used."}
    )
    other_subsets: str = field(default=None)
    survey_size: int = field(
        default=8,
        metadata={"help": "Size of survey question pool."}
    )
    context_length: int = field(
        default=8,
        metadata={"help": "(Maximum) context length."}
    )
    controversial_only: bool = field(
        default=True,
        metadata={"help": "Whether to only generate controversial data points."}
    )
    num_duplicates: int = field(
        default=1,
        metadata={"help": "Number of times each data point is repeated."}
    )
    fixed_context_length: bool = field(
        default=False,
        metadata={"help": "Whether to fix the context to the maximum length."}
    )
    random_contexts: bool = field(
        default=False,
        metadata={"help": "Whether to include non-controversial pairs in context."}
    )


def load_input_dataset(args: ScriptArguments):
    if args.with_embeddings:
        from data_utils.data_processing import generate_embeddings_with_llm

        return generate_embeddings_with_llm(args)

    data_file = os.path.join(args.data_path, args.data_subset, f"{args.data_split}.jsonl")
    if not os.path.exists(data_file):
        raise FileNotFoundError(f"Could not find dataset split: {data_file}")
    return load_dataset("json", data_files=data_file, split="train")


def as_bool(value) -> bool:
    if isinstance(value, bool):
        return value
    if value is None:
        return False
    if isinstance(value, str):
        return value.strip().lower() in {"1", "true", "yes", "y", "t"}
    return bool(value)


def generate_contexts(args: ScriptArguments, input_dataset, survey_dataset):
    output_dir = os.path.join(args.output_dir, f"{args.model_type}", f"{args.data_subset}")
    os.makedirs(output_dir, exist_ok=True)

    if args.controversial_only:
        input_dataset = input_dataset.filter(lambda x: as_bool(x.get("controversial")))

    dataset_size = len(input_dataset)
    num_copies = args.num_duplicates if args.data_split == "train" else 1
    dataset_list = []

    def random_choice(max_context_length: int, survey_size: int):
        if max_context_length > survey_size:
            raise ValueError("Context length is larger than survey size.")

        while True:
            if args.fixed_context_length:
                context_length = max_context_length
            elif args.other_subsets == "84":
                context_length = random.randint(1, max_context_length)
            else:
                context_length = random.randint(2, max_context_length)

            chosen_ids = np.random.choice(survey_size, context_length, replace=False)
            chosen_dataset = [row for idx, row in enumerate(survey_dataset) if idx in chosen_ids]
            if args.other_subsets != "single":
                return chosen_dataset, context_length

            satisfied_sets = [set(row["satisfied_subset"]) for row in chosen_dataset]
            shared = set.intersection(*satisfied_sets)
            if len(shared) == 1:
                return chosen_dataset, context_length
            if context_length == survey_size:
                raise ValueError("Please choose another random seed.")

    for _ in range(num_copies):
        output_dataset = deepcopy(input_dataset)
        context_lengths = []
        contexts = []
        for _row_id in tqdm(range(dataset_size)):
            row_contexts = []
            context_dataset, context_length = random_choice(args.context_length, args.survey_size)
            context_lengths.append(context_length)
            for context_row in context_dataset:
                context_entry = {
                    "original_id": context_row["Index"],
                    "prompt": context_row.get("prompt", ""),
                    "chosen": context_row.get("chosen", ""),
                    "rejected": context_row.get("rejected", ""),
                }
                if args.with_embeddings:
                    context_entry.update(
                        {
                            "embedding_chosen": context_row["embeddings"]["embedding_chosen"],
                            "embedding_rejected": context_row["embeddings"]["embedding_rejected"],
                        }
                    )
                row_contexts.append(context_entry)
            contexts.append(row_contexts)
        output_dataset = output_dataset.add_column("context_length", context_lengths)
        output_dataset = output_dataset.add_column("contexts", contexts)
        dataset_list.append(output_dataset)

    output = concatenate_datasets(dataset_list)
    output.to_json(os.path.join(output_dir, f"{args.data_split}.jsonl"))
    return output


if __name__ == "__main__":
    seed = 0
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    parser = HfArgumentParser(ScriptArguments)
    script_args: ScriptArguments = parser.parse_args_into_dataclasses()[0]
    print(script_args)
    dataset = load_input_dataset(script_args)
    if not script_args.random_contexts:
        survey_options = dataset.filter(lambda x: as_bool(x.get("survey_options")))
    else:
        survey_options = dataset.filter(lambda x: "survey_options" in x)
    survey_ids = np.random.choice(range(len(survey_options)), script_args.survey_size, replace=False)
    print(survey_ids)
    survey_path = os.path.join(script_args.data_path, script_args.data_subset, f"survey_{script_args.survey_size}.jsonl")
    if script_args.data_split == "train":
        survey_data = survey_options.filter(lambda example, idx: idx in survey_ids, with_indices=True)
        survey_data.to_json(survey_path)
    else:
        survey_data = load_dataset("json", data_files=survey_path, split="train")
    generate_contexts(script_args, dataset, survey_data)
