#!/usr/bin/env python3
"""Helpers for preprocessing JSONL preference datasets."""

import os
import random
from copy import deepcopy
from dataclasses import dataclass, field
from typing import Optional

import numpy as np
import torch
from datasets import concatenate_datasets, load_dataset
from tqdm import tqdm
from transformers import (
    AutoModelForCausalLM,
    AutoModelForSequenceClassification,
    AutoTokenizer,
    HfArgumentParser,
)


@dataclass
class ScriptArguments:
    output_dir: Optional[str] = field(
        metadata={"help": "Directory where the new dataset will be stored."},
    )
    data_path: str = field(
        metadata={"help": "Directory where the original data is stored."}
    )
    data_subset: str = field(
        default="helpful",
        metadata={
            "help": "Which subset of the data to use."
        },
    )
    data_split: str = field(
        default="test",
        metadata={
            "help": "Which split of the data to use."
        },
    )
    dataset_size: int = field(
        default=0,
        metadata={"help": "The size of the subset of the data to use"},
    )
    model_type: str = field(
        default="vicuna",
        metadata={
            "help": "Embedding backbone name."
        }
    )
    embed_dim: int = field(
        default=4096,
        metadata={
            "help": "Dimension of the embeddings generated by the LLM."
        }
    )
    max_length: int = field(
        default=1024,
        metadata={
            "help": "Maximum token length of the inputs."
        }
    )
    with_embeddings: bool = field(
        default=True,
        metadata={
            "help": "Whether embeddings are generated during preprocessing."
        }
    )
    synthetic_dataset: bool = field(
        default=False,
        metadata={
            "help": "Whether a synthetic dataset is used."
        }
    )
    other_subsets: str = field(default=None)


def load_preference_json_dataset(args: ScriptArguments):
    data_file = os.path.join(args.data_path, args.data_subset, f"{args.data_split}.jsonl")
    if not os.path.exists(data_file):
        raise FileNotFoundError(f"Could not find dataset split: {data_file}")
    return load_dataset("json", data_files=data_file, split="train")


def preprocess_preference_dataset(dataset, tokenizer, max_length: int):
    def _tokenize(batch):
        chosen_tokens = tokenizer(
            [str(text or "") for text in batch["chosen"]],
            truncation=True,
            max_length=max_length,
            add_special_tokens=False,
        )
        rejected_tokens = tokenizer(
            [str(text or "") for text in batch["rejected"]],
            truncation=True,
            max_length=max_length,
            add_special_tokens=False,
        )
        return {
            "input_ids_chosen": chosen_tokens["input_ids"],
            "input_ids_rejected": rejected_tokens["input_ids"],
        }

    return dataset.map(
        _tokenize,
        batched=True,
        load_from_cache_file=False,
    )


def generate_embeddings_with_llm(args: ScriptArguments, input_dataset=None):
    """Generate fixed text embeddings for chosen/rejected responses."""
    if not args.synthetic_dataset:
        input_dataset = load_preference_json_dataset(args)

    if args.model_type == "vicuna":
        ckpt = "lmsys/vicuna-7b-v1.5"
        tokenizer = AutoTokenizer.from_pretrained(ckpt, use_auth_token=True)
        model = AutoModelForCausalLM.from_pretrained(
            ckpt,
            load_in_4bit=True,
            bnb_4bit_compute_dtype=torch.bfloat16,
            device_map="auto",
        )
    elif args.model_type == "llama-3.2-1B-instruct":
        ckpt = "meta-llama/Llama-3.2-1B-Instruct"
        tokenizer = AutoTokenizer.from_pretrained(ckpt, use_auth_token=True)
        model = AutoModelForCausalLM.from_pretrained(
            ckpt,
            load_in_4bit=True,
            bnb_4bit_compute_dtype=torch.bfloat16,
            device_map="auto",
        )
        args.embed_dim = model.config.hidden_size
    elif args.model_type == "llama-3.2-3B-instruct":
        ckpt = "meta-llama/Llama-3.2-3B-Instruct"
        tokenizer = AutoTokenizer.from_pretrained(ckpt, use_auth_token=True)
        model = AutoModelForCausalLM.from_pretrained(
            ckpt,
            load_in_4bit=True,
            bnb_4bit_compute_dtype=torch.bfloat16,
            device_map="auto",
        )
        args.embed_dim = model.config.hidden_size
    elif args.model_type == "llama-3.1-8B-instruct":
        ckpt = "meta-llama/Llama-3.1-8B-Instruct"
        tokenizer = AutoTokenizer.from_pretrained(ckpt, use_auth_token=True)
        model = AutoModelForCausalLM.from_pretrained(
            ckpt,
            load_in_4bit=True,
            bnb_4bit_compute_dtype=torch.bfloat16,
            device_map="auto",
        )
        args.embed_dim = model.config.hidden_size
    elif args.model_type == "gpt2":
        tokenizer = AutoTokenizer.from_pretrained("gpt2", use_auth_token=True)
        model = AutoModelForSequenceClassification.from_pretrained(
            "gpt2", num_labels=args.embed_dim, torch_dtype=torch.bfloat16
        )
        model.score.weight.data *= 0.01
    else:
        return input_dataset

    model.to("cuda")

    if tokenizer.pad_token_id is None:
        tokenizer.pad_token = tokenizer.eos_token
        tokenizer.padding_side = "right"
    model.config.pad_token_id = tokenizer.pad_token_id

    preprocessed_dataset = preprocess_preference_dataset(
        input_dataset,
        tokenizer,
        max_length=args.max_length,
    )

    input_dataset = input_dataset.filter(
        lambda example, idx: len(preprocessed_dataset[idx]["input_ids_chosen"]) <= args.max_length
        and len(preprocessed_dataset[idx]["input_ids_rejected"]) <= args.max_length,
        with_indices=True,
    )
    preprocessed_dataset = preprocessed_dataset.filter(
        lambda example: len(example["input_ids_chosen"]) <= args.max_length
        and len(example["input_ids_rejected"]) <= args.max_length
    )

    embeddings = []
    for row_id in tqdm(range(len(preprocessed_dataset))):
        emb = {}
        for key in ["chosen", "rejected"]:
            tokens = tokenizer.pad(
                {"input_ids": preprocessed_dataset[row_id][f"input_ids_{key}"]},
                padding="max_length",
                max_length=args.max_length,
                return_tensors="pt",
            )
            token_length = len(preprocessed_dataset[row_id][f"input_ids_{key}"])
            input_ids = tokens["input_ids"].unsqueeze(0).to("cuda")
            attention_mask = tokens["attention_mask"].unsqueeze(0).to("cuda")
            with torch.no_grad():
                hidden = model(
                    input_ids=input_ids,
                    attention_mask=attention_mask,
                    output_hidden_states=True,
                ).hidden_states[-1]
                vec = hidden[0][token_length - 1].float().cpu().tolist()
                assert len(vec) == args.embed_dim, "embed_dim mismatch"
                emb[f"embedding_{key}"] = vec
        embeddings.append(emb)

    return input_dataset.add_column("embeddings", embeddings)


def generate_contexts(args: ScriptArguments, input_dataset):
    """Generate random controversial contexts without a fixed survey pool."""
    output_dir = os.path.join(args.output_dir, f"{args.model_type}", f"{args.data_subset}")
    os.makedirs(output_dir, exist_ok=True)

    dataset_size = len(input_dataset)
    dataset_list = []
    for _ in range(1):
        context_dataset = deepcopy(input_dataset)
        context_lengths = [8] * dataset_size
        if "context_length" in context_dataset.column_names:
            context_dataset = context_dataset.remove_columns("context_length")
        context_dataset = context_dataset.add_column("context_length", context_lengths)
        contexts = []
        for row_id in tqdm(range(dataset_size)):
            row_contexts = []
            num_context = 0
            controversial_subset = input_dataset.filter(lambda example: bool(example.get("controversial")))
            controversial_size = len(controversial_subset)
            while num_context < context_lengths[row_id]:
                random_id = np.random.randint(controversial_size)
                context_data = controversial_subset[random_id]
                if not args.synthetic_dataset and input_dataset[row_id]["prompt"] == context_data["prompt"]:
                    continue
                context_entry = {
                    "original_id": context_data["Index"],
                    "prompt": context_data.get("prompt", ""),
                    "chosen": context_data.get("chosen", ""),
                    "rejected": context_data.get("rejected", ""),
                }
                if args.with_embeddings:
                    context_entry.update(
                        {
                            "embedding_chosen": context_data["embeddings"]["embedding_chosen"],
                            "embedding_rejected": context_data["embeddings"]["embedding_rejected"],
                        }
                    )
                row_contexts.append(context_entry)
                num_context += 1
            contexts.append(row_contexts)
        context_dataset = context_dataset.add_column("contexts", contexts)
        dataset_list.append(context_dataset)

    output = concatenate_datasets(dataset_list)
    output.to_json(os.path.join(output_dir, f"{args.data_split}.jsonl"))
    return output


if __name__ == "__main__":
    seed = 0
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    parser = HfArgumentParser(ScriptArguments)
    script_args: ScriptArguments = parser.parse_args_into_dataclasses()[0]
    print(script_args)
    dataset = generate_embeddings_with_llm(script_args)
    generate_contexts(script_args, dataset)
